version: '2.0'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    ports :
      - "9001:9000"
    links :
      - mysql
    restart : always
    volumes:
      - ./apps:/mnt/apps
      - ./php:/usr/local/etc/php
  nginx:
    image: nginx:1.10.3
    container_name: nginx
    ports:
      - 1024:80
    links:
      - php
    restart : always
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./nginx/config:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
  mysql:
    image: mysql:5.6
    container_name : mysql
    ports :
        - "3307:3306"
    restart : always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    volumes:
      - ./database:/var/lib/mysql
